config/routes.rb
BtcApp::Application.routes.draw do
  devise_for :users

  root to: "welcome#index"
  resources :donors
  resources :recipients
  resources :pres
  resources :abouts
  namespace :admin do
    resources :donors
    resources :recipients
    resources :pres
    resources :abouts
  end
end

app/models/about.rb
class About < ActiveRecord::Base
  attr_accessible :content
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  attr_accessible :address, :name, :num, :type_desc
end

app/models/pre.rb
class Pre < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  attr_accessible :age, :name, :school
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :admin
  # attr_accessible :title, :body
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
    @about = About.last
  end

  def new
    if current_user.admin == true
      @about = About.new
    end   
  end

  def create
    @about = About.create(params[:about])
  end

  def edit
    if current_user.admin == true
      @about = About.last
    end 
  end

  def update
    @about = About.last
    @about.update_attributes(params[:pre])
    redirect_to admin_abouts_path
  end
end

app/controllers/admin/abouts_controller.rb
class Admin::AboutsController < ApplicationController
  before_filter :admin
  def index
    @about = About.last
  end

  def new
    @about =About.new
  end

  def create
    @about = About.create(params[:about])
  end

  def edit
    @about = About.last
  end

  def update
    @about = About.last
    @about.update_attributes(params[:about])

    redirect_to admin_abouts_path
  end

  protected

  def admin
    if signed_in? == false
      redirect_to root_path
    end  
  end
end

app/controllers/admin/donors_controller.rb
class Admin::DonorsController < ApplicationController
  before_filter :admin

  def index
      @donor = Donor.page(params[:page]).per(15).order("id DESC")
  end

  def new
    @donor = Donor.new
  end

  def create
    @donor = Donor.create(params[:donor])
    if save
      redirect_to admin_donors_path
    else
      render "new"
    end
  end

  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy
  end

  def edit
    @donor = Donor.find(params[:id])
  end

  def update
    @donor = Donor.find(params[:id])
    @donor.update_attributes(params[:donor])

    redirect_to admin_donors_path
  end

  protected

  def admin
    if signed_in? == false
      redirect_to root_path
    end  
  end
end

app/controllers/admin/pres_controller.rb
class Admin::PresController < ApplicationController
  before_filter :admin
  def index
    @pre = Pre.page(params[:page]).per(20).order("id DESC")
  end

  def new
    @pre = Pre.new
  end

  def create
    @pre = Pre.create(params[:pre])
  end

  def destroy
    @pre = Pre.find(params[:id])
    @pre.destroy
  end

  def edit
    @pre = Pre.find(params[:id])
  end

  def update
    @pre = Pre.find(params[:id])
    @pre.update_attributes(params[:pre])
    redirect_to admin_pres_path
  end


  protected

  def admin
    if signed_in? == false
      redirect_to root_path
    end  
  end
end

app/controllers/admin/recipients_controller.rb
class Admin::RecipientsController < ApplicationController
  before_filter :admin
  def index
    @recipient = Recipient.page(params[:page]).per(15).order("id DESC")
  end

  def new
    @recipient = Recipient.new
  end

  def create
    @recipient = Recipient.create(params[:recipient])
  end

  def destroy
    @recipient = Recipient.find(params[:id])
    @recipient.destroy
  end

  def edit
    @recipient = Recipient.find(params[:id])
  end

  def update
    @recipient = Recipient.find(params[:id])
    @recipient.update_attributes(params[:recipient])
    redirect_to root_path
  end

  def admin
    if signed_in? == false
      redirect_to root_path
    end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_locale
  protect_from_forgery
  def after_sign_in_path_for(resource_or_scope)    
    admin_donors_path  
  end


  def set_locale
    # 可以將 ["en", "zh-TW"] 設定為 VALID_LANG 放到 config/environment.rb 中
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  def index
    @donor = Donor.page(params[:page]).per(5).order("id DESC")
  end

  def new
    @donor = Donor.new
  end

  def create
    @donor = Donor.create(params[:donor])

    redirect_to admin_donors_path
   
  end

  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy
    redirect_to admin_donors_path
  end

  def edit
    @donor = Donor.find(params[:id])
  end

  def update
    @donor = Donor.find(params[:id])
    @donor.update_attributes(params[:donor])

    redirect_to root_path
  end
end

app/controllers/pres_controller.rb
class PresController < ApplicationController
  def index
    @pre = Pre.page(params[:page]).per(10).order("id DESC")
  end

  def new
    @pre = Pre.new
  end

  def create
    @pre = Pre.create(params[:pre])
    redirect_to admin_pres_path
  end

  def destroy
    @pre = Pre.find(params[:id])
    @pre.destroy
    redirect_to admin_pres_path
  end
  
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  def index
    @recipient = Recipient.page(params[:page]).per(5).order("id DESC")
  end

  def new
    @recipient = Recipient.new
  end

  def create
    @recipient = Recipient.create(params[:recipient])
    redirect_to admin_recipients_path
  end

  def edit
    @recipient = Recipient.find(params[:id])
  end

  def update
    @recipient = Recipient.find(params[:id])
    @recipient.update_attributes(params[:recipient])
    redirect_to root_path
  end

  def destroy
    @recipient = Recipient.find(params[:id])
    @recipient.destroy
    redirect_to admin_recipients_path
  end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @donor = Donor.page(params[:page]).per(18).order("id DESC")
    @recipient = Recipient.page(params[:fuck_page]).per(18).order("id DESC")
    @pre = Pre.page(params[:pres_page]).per(3).order("id DESC")
    @about = About.last
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/abouts_helper.rb
module Admin::AboutsHelper
end

app/helpers/admin/donors_helper.rb
module Admin::DonorsHelper
end

app/helpers/admin/pres_helper.rb
module Admin::PresHelper
end

app/helpers/admin/recipients_helper.rb
module Admin::RecipientsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/pres_helper.rb
module PresHelper
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/abouts/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10 offset1 center">
        <%=raw @about.content%>
    </div>
  </div>
</div>
<script type="text/javascript">
  var sdonor= document.getElementsByTagName("li");
  for (var i = 0; i < sdonor.length; i++ ) {
    {
      sdonor[2].setAttribute("class","active");
    }
  }
</script>

app/views/admin/abouts/edit.html.erb
<h1 class="text-center muted">关于我们</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @about, :url => { :controller => 'abouts', :action => 'update', :id => @about } do |pre| %>
          <%= pre.label :content, "新闻内容" %>
          <%= pre.kindeditor :content, class: "span7" %>
          <p style="padding-top:2%">
          <%= pre.submit "更新", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/abouts/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10 offset1 center">
        <%=raw @about.content%>
    </div>
  </div>
</div>

app/views/admin/abouts/new.html.erb
<h1 class="text-center muted">添加新闻</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @about do |f| %>
          <%= f.label :content, "内容" %>
          <%= f.kindeditor :content %>
          <p style="padding-top: 2%">
          <%= f.submit "创建", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/donors/edit.html.erb
<h1 class="text-center muted">捐助明细</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @donor, :url => { :controller => 'donors', :action => 'update', :id => @donor } do |donor| %>
          <%= donor.label :name, "名字" %>
          <%= donor.text_field :name, class: "span2" %>
          <%= donor.label :address, "地址" %>
          <%= donor.text_field :address, class: "span7" %>
          <%= donor.label :type_desc, "捐助类型" %>
          <%= donor.text_field :type_desc %>
          <%= donor.label :num, "数量" %>
          <%= donor.text_field :num %>
          <p>
          <%= donor.submit "更新", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/donors/index.html.erb
<h1 class="text-center muted">捐助明细</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
    </div>

    <div class="span7 " style="background-color: white;">
    <!--Sidebar content-->
    <h2 style="padding-left: 1%">
      <%= link_to "新建", new_admin_donor_path, class: "btn btn-primary"%>
    </h2>
    <table class="table table-bordered" >
    <thead>
      <tr>
        <th>姓名</th>
        <th>地址</th>
        <th>捐助类别</th>
        <th>数量</th>
        <th>管理</th>
      </tr>
    </thead>
    <% @donor.each do |d|%>
    <tbody>
      <tr>
        <td >
          <%= d.name %>
        </td>
        <td >
          <%= d.address %>
        </td>
        <td>
          <%= d.type_desc %>
        </td>
        <td>
          <%= d.num %>
        </td>
        <td>
          <%= link_to "编辑", edit_admin_donor_path(d)%>
          <%= link_to "删除", d, method: :delete %>
        </td> 

      </tr>
    </tbody>
    <% end %>
    </table>
      <div class="text-center">
        <%= paginate @donor %>
      </div>
    </div>
  </div>
</div>

app/views/admin/donors/new.html.erb
<h1 class="text-center muted">添加捐助者</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @donor do |f|%>
          <%= f.label :name, "姓名" %>
          <%= f.text_field :name %>
          <%= f.label :address, "地址" %>
          <%= f.text_field :address %>
          <%= f.label :type_desc, "捐助类型" %>
          <%= f.text_field :type_desc %>
          <%= f.label :num, "数量" %>
          <%= f.text_field :num %>
          <p><%= f.submit "创建", class: "btn btn-primary"%></p>
        <% end %>        
      </div>
    </div>
  </div>
</div>

app/views/admin/pres/edit.html.erb
<h1 class="text-center muted">新闻管理</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @pre, :url => { :controller => 'pres', :action => 'update', :id => @pre } do |pre| %>
          <%= pre.label :titile, "标题" %>
          <%= pre.text_field :title, class: "span7" %>
          <%= pre.label :content, "新闻内容" %>
          <%= pre.kindeditor :content, class: "span7" %>
          <p style="padding-top:2%">
          <%= pre.submit "更新", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pres/index.html.erb
<h1 class="text-center muted">新闻管理</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
    </div>

    <div class="span7 " style="background-color: white;">
    <!--Sidebar content-->
    <h2 style="padding-left: 1%">
      <%= link_to "新建", new_admin_pre_path, class: "btn btn-primary"%>
    </h2>
    <table class="table table-bordered" >
    <thead>
      <tr>
        <th>新闻标题</th>
        <th>操作</th>
      </tr>
    </thead>
    <% @pre.each do |p|%>
    <tbody>
      <tr>
        <td >
          <%= p.title %>
        </td>
        <td >
          <%= link_to "编辑", edit_admin_pre_path(p)%>
          <%= link_to "删除",p , method: :delete %>
        </td>
      </tr>
    </tbody>
    <% end %>
    </table>
      <div class="text-center">
          <%= paginate @pre %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pres/new.html.erb
<h1 class="text-center muted">添加新闻</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @pre do |f| %>
          <%= f.label :title, "标题" %>
          <%= f.text_field :title %>
          <%= f.label :content, "内容" %>
          <%= f.kindeditor :content %>
          <p style="padding-top: 2%">
          <%= f.submit "创建", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/recipients/edit.html.erb
<h1 class="text-center muted">捐助明细</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>

    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @recipient, :url => { :controller => 'recipients', :action => 'update', :id => @recipient } do |recipient| %>
          <%= recipient.label :name, "姓名" %>
          <%= recipient.text_field :name, class: "span2" %>
          <%= recipient.label :school, "学校" %>
          <%= recipient.text_field :school, class: "span7" %>
          <%= recipient.label :age, "年龄" %>
          <%= recipient.text_field :age %>
          <p>
          <%= recipient.submit "更新", class: "btn btn-primary"%>
          </p>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/recipients/index.html.erb
<h1 class="text-center muted">受捐者明细</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
    </div>
<div class="span7" style="background-color: white;">
  <h2 style="padding-left: 1%">
    <%= link_to "新建", new_admin_recipient_path, class: "btn btn-primary"%>
  </h2>
  <table class="table table-bordered" >
    <thead>
      <tr>
        <th>姓名</th>
        <th>学校</th>
        <th>年龄</th>
        <th>管理</th>
      </tr>
    </thead>
    <% @recipient.each do |r|%>
    <tbody>
      <tr>
        <td >
          <%= r.name %>
        </td>
        <td >
          <%= r.school %>
        </td>
        <td>
          <%= r.age%>
        </td>
        <td>
          <%= link_to "编辑", edit_admin_recipient_path(r)%>
          <%= link_to "删除", r, method: :delete %>
        </td> 
      </tr>
    </tbody>
    <% end %>
  </table>
  <div class="text-center">
  <%= paginate @recipient %>
  </div>
</div>

</div>
</div>

app/views/admin/recipients/new.html.erb
<h1 class="text-center muted">添加被捐助者</h1>
<div class="container-fluid" style= "padding-bottom: 2%">
  <div class="row-fluid">
    <div class="span2 offset1">
      <div style="background-color: white;">
      <%= render "shared/left"%>
      </div>
      </div>
    <div class="span7 " style="background-color: white;">
      <div style="padding:2%">
        <%= form_for @recipient do |f|%>
          <%= f.label :name, "姓名" %>
          <%= f.text_field :name %>
          <%= f.label :school, "学校" %>
          <%= f.text_field :school %>
          <%= f.label :age, "年龄" %>
          <%= f.text_field :age %>
          <p>
          <%= f.submit "创建", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/donors/_index.html.erb
  <div class="donors">
    <table class="table table-bordered" >
    <thead>
      <tr >
        <th><%= t("donors.name")%></th>
        <th><%= t("donors.type")%></th>
        <th><%= t("donors.num") %></th>
        <th><%= t("donors.remark")%></th>
      </tr>
    </thead>
    <% @donor.each do |d|%>
    <tbody  style="font-family: 'Courier New';">
      <tr>
        <td >
          <%= d.name %>
        </td>
        <td>
            <%= d.type_desc %>
        </td>
        <td >
          <%= d.num %>
        </td>
        <td >
          <%= d.address %>
        </td>
        
        
      </tr>
    </tbody>
    <% end %>
    </table>
      <div class="text-center" onclick="window.location = '#whatwedo'">
        <%= paginate @donor, :remote => true%>
      </div>

</div>

app/views/pres/_index.html.erb
<div class="pres">
  <% @pre.each do |p|%>
  <div style="background-color: white;border-radius: 15px;padding-top: 1%">
  <div class="row" >
     <!--新闻开始迭代-->
                            
      <div class="span12 centered">
          <h2><%= p.title %></h2>
          <p class="text-center"><%= p.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s%></p>
          <div class="breaker"><span class="left"></span><div class="feather"></div><span class="right"></span></div>
      </div>
  </div>
  <div class="row">
      <div class="span12 centered">
          <div style="padding:2%">
            <div style="padding:2%">
              <%=raw p.content %>
            </div>
          </div>
      </div>
    </div>
    </div>
     <div class="row" style="background-color: #F5F5F5;">
      <div class="span12 centered">
          <div style="padding:2%">
            <div style="padding:2%">
              
            </div>
          </div>
      </div>
    </div>
    
  
  <% end %>
  <div class="text-center" onclick="window.location = '#about'">
    <%= paginate @pre, :remote => true, :param_name => :pres_page%>
  </div>
</div>

app/views/recipients/_index.html.erb
<div class="recipients">
  <table class="table table-bordered" >
    <thead>
      <tr>
        <th><%= t("recipients.name")%></th>
        <th><%= t("recipients.school")%></th>
        <th><%= t("recipients.age")%></th>
      </tr>
    </thead>
    <% @recipient.each do |r|%>
    <tbody>
      <tr>
        <td >
          <%= r.name %>
        </td>
        <td >
          <%= r.school %>
        </td>
        <td>
          <%= r.age%>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <div class="text-center" onclick="window.location = '#services'">
  <%= paginate @recipient, :remote => true, :param_name => :fuck_page%>
  </div>
</div>